### ISSUE TITLE
At least give due credit to the library you using in your readme & website

### ISSUE THREAD

**Issue by chinchang** [hkirat/notification-logger#14]
This is based on https://github.com/chinchang/screenlog.js

& website design is copied from https://kushagragour.in/lab/hint/

**Comment by hkirat** [comment]
Hey
Added credits to the README and took down the website.
Please let me know if there's anything else that needs to be done
Regards
Harkirat

**Comment by hkirat** [comment]
Closed via 6a30c

**Comment by hkirat** [comment]
Closed via #6a30c

**Comment by hkirat** [comment]
Closed via 6a30c29d044fc66f10fa39d4724cbcb502133f59
