### ISSUE TITLE
example.html does not work on Ubuntu 16.04 Chrome version 53.0.2785.92 (64-bit)

### ISSUE THREAD

**Issue by jarifibrahim** [hkirat/notification-logger#8]
The notification permission request pop up does not appear on chrome.

Console contains

```
"title"                           notification-logger.js:23 2 
"title"                           example.html:32 2
```

The notification-logger demo works fine.

**Comment by hkirat** [comment]
Try creating a python server using the following command
python -m SimpleHTTPServer
Now go to localhost:8000 and check index.html. Should work.A lot of people have been facing this problem.
Need to get to the bottom of this.

**Comment by jarifibrahim** [comment]
Thanks! It worked!
